'use strict';
const D=window.STOCK_DATA,$=s=>document.querySelector(s),won=v=>Math.round(v/100)*100,p=v=>won(v).toLocaleString('ko-KR'),pct=v=>(v>=0?'+':'')+(v*100).toFixed(1)+'%';
$('#asof').textContent=D.asOf;$('#generated').textContent=new Date(D.generatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' KST';
$('#cards').innerHTML=D.stocks.map(s=>{const f=s.forecasts.at(-1);return `<article class="card" style="--stock:${s.color}"><div class="ticker">${s.symbol} / KOSPI</div><h2>${s.name}</h2><p>12월 말 기준 시나리오</p><div class="price">${p(f.base)} <small>원</small></div><div class="delta">기준 종가 대비 ${pct(f.base/s.last-1)}</div><p>실제 종가 ${s.last.toLocaleString('ko-KR')}원</p><p>하락 ${p(f.low)} ~ 상승 ${p(f.high)}원</p></article>`}).join('');
$('#forecastRows').innerHTML=D.stocks.flatMap(s=>s.forecasts.slice(1).map(f=>`<tr><td style="color:${s.color}">${s.name}</td><td>${f.date}</td><td>${p(f.low)}원</td><td>${p(f.base)}원</td><td>${p(f.high)}원</td><td>${pct(f.base/s.last-1)}</td></tr>`)).join('');
$('#testRows').innerHTML=D.stocks.map(s=>`<tr><td>${s.name}</td><td><span class="pill ${s.backtest.mape>s.backtest.naiveMape?'bad':''}">${s.backtest.mape.toFixed(1)}%</span></td><td>${s.backtest.naiveMape.toFixed(1)}%</td><td>${s.backtest.folds.filter(f=>f.covered).length} / ${s.backtest.folds.length}회</td><td>${(s.volatility*100).toFixed(1)}%</td><td>${pct(s.drawdown)}</td></tr>`).join('');
function render(){const all=$('#stock').value==='all',stocks=all?D.stocks:D.stocks.filter(s=>s.symbol===$('#stock').value),band=$('#band').checked;let start=new Date(D.asOf+'T00:00:00Z');start.setUTCMonth(start.getUTCMonth()-Number($('#period').value));const from=start.toISOString().slice(0,10),series=stocks.map(s=>({s,h:s.history.filter(v=>v.date>=from),f:s.forecasts}));const val=(v,s)=>all?v/s.last*100:v;let values=[];series.forEach(({s,h,f})=>{values.push(...h.map(v=>val(v.close,s)),...f.map(v=>val(v.base,s)));if(band)values.push(...f.flatMap(v=>[val(v.low,s),val(v.high,s)]));});let lo=Math.min(...values),hi=Math.max(...values);const pad=(hi-lo)*.12;lo=Math.max(0,lo-pad);hi+=pad;const W=1080,H=430,L=88,R=25,T=35,B=48;const begin=Date.parse(from),end=Date.parse(D.target),x=d=>L+(Date.parse(d)-begin)/(end-begin)*(W-L-R),y=v=>H-B-(v-lo)/(hi-lo)*(H-T-B),line=(arr,key,s)=>arr.map((v,i)=>(i?'L':'M')+x(v.date).toFixed(2)+','+y(val(v[key],s)).toFixed(2)).join(' ');let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${all?'세 종목 기준가 100 비교':stocks[0].name+' 원화'} 실제 및 예상 주가 차트"><title>실제 주가와 2026년 12월까지의 통계 시나리오. 상세 예상값은 아래 테이블 참조.</title><rect x="${x(D.asOf)}" y="${T}" width="${x(D.target)-x(D.asOf)}" height="${H-T-B}" fill="#203442" opacity=".42"/>`;
for(let i=0;i<=5;i++){let v=lo+(hi-lo)*i/5;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#2b394c"/><text x="${L-12}" y="${y(v)+4}" text-anchor="end" fill="#9dacc1" font-size="11">${all?v.toFixed(0):Math.round(v).toLocaleString('ko-KR')}</text>`;}
let month=new Date(from+'T00:00:00Z');month.setUTCDate(1);month.setUTCMonth(month.getUTCMonth()+1);while(month.getTime()<=end){const d=month.toISOString().slice(0,10);svg+=`<text x="${x(d)}" y="${H-17}" text-anchor="middle" fill="#9dacc1" font-size="11">${month.getUTCMonth()+1}월</text>`;month.setUTCMonth(month.getUTCMonth()+1);}
svg+=`<line x1="${x(D.asOf)}" x2="${x(D.asOf)}" y1="${T}" y2="${H-B}" stroke="#778da5" stroke-dasharray="4 5"/><text x="${x(D.asOf)+10}" y="20" fill="#a4b9ca" font-size="11">예상 구간 →</text><text x="${L}" y="20" fill="#a4b9ca" font-size="11">${all?'기준일 종가 = 100':'원 (KRW)'}</text>`;
series.forEach(({s,h,f})=>{if(band){let path=line(f,'high',s)+' '+[...f].reverse().map(v=>'L'+x(v.date)+','+y(val(v.low,s))).join(' ')+' Z';svg+=`<path d="${path}" fill="${s.color}" opacity=".09"/>`;}svg+=`<path d="${line(h,'close',s)}" stroke="${s.color}" stroke-width="2.5" fill="none"/><path d="${line(f,'base',s)}" stroke="${s.color}" stroke-width="2.5" stroke-dasharray="6 5" fill="none"/>`;f.forEach(v=>{svg+=`<circle cx="${x(v.date)}" cy="${y(val(v.base,s))}" r="4" fill="${s.color}"><title>${s.name} ${v.date}: 기준 ${p(v.base)}원 / 하락 ${p(v.low)}원 / 상승 ${p(v.high)}원</title></circle>`;});});svg+='</svg>';$('#chart').innerHTML=svg;$('#chartnote').innerHTML=stocks.map(s=>`<span style="color:${s.color}">● ${s.name}</span>`).join('　')+(all?'　각 종목의 9/11 종가를 100으로 환산했습니다.':'　실제 종가와 예상 가격을 원화로 표시합니다.');}
['#stock','#period','#band'].forEach(id=>$(id).addEventListener('change',render));render();
