'use strict';
const M=window.FUNDAMENTAL,D=window.STOCK_DATA,$=s=>document.querySelector(s),money=v=>(Math.round(v/100)*100).toLocaleString('ko-KR'),pct=v=>(v>=0?'+':'')+(v*100).toFixed(1)+'%';
const names={stress:'악화 가정',base:'중립 가정',upside:'개선 가정'},settings=structuredClone(M.presets);let selected='base';
const fields=[['kr','연말 한국 기준금리 (%)',0,8,.25],['us','연말 미국 금리 중간값 (%)',0,10,.025],['fx','연말 원/달러 (원)',900,2000,.1],['robot','현대차 로봇 연내 이벤트 확률 가정 (%)',0,100,5],['robotImpact','이벤트 발생 시 현대차 주가 순효과 (%)',-30,50,1]];
const labels=['실적','환율','기타 이익충격','평가배수','금리','로봇 이벤트'];
function controls(){
 $('#macroControls').innerHTML=fields.map(([k,l,min,max,step])=>`<label>${l}<input aria-label="${l}" type="number" data-field="${k}" min="${min}" max="${max}" step="${step}" value="${settings[selected][k]}"></label>`).join('');
 $('#stockControls').innerHTML=D.stocks.map((s,i)=>`<article><h3 style="color:${s.color}">${s.name}</h3><p>Q2 실제 영업이익 ${M.facts.op[i].toFixed(2)}조원</p>${[['growth','Q4 영업이익 / Q2 변화 (%)',-80,150],['multiple','평가배수 변화 (%)',-60,100],['other','관세·경기 등 추가 이익충격 (%)',-60,60]].map(([k,l,min,max])=>`<label>${l}<input type="number" aria-label="${s.name} ${l}" data-field="${k}" data-index="${i}" min="${min}" max="${max}" step="1" value="${settings[selected][k][i]}"></label>`).join('')}<p>성장률에 이미 포함한 충격을 추가 이익충격에 다시 넣지 마세요.</p></article>`).join('');
 document.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{if(el.value===''||!el.validity.valid){$('#inputStatus').textContent='입력 범위 또는 단위를 확인하세요. 아래 결과는 마지막 유효 설정 기준입니다.';$('#download').hidden=true;return;}const k=el.dataset.field,n=Number(el.value);if(el.dataset.index!==undefined)settings[selected][k][Number(el.dataset.index)]=n;else settings[selected][k]=n;update();}));
 document.querySelectorAll('[data-scenario]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.scenario===selected)));
 $('#scenarioDescription').textContent=`현재 편집: ${names[selected]} · 모든 미래 입력값은 수정 가능한 가정입니다. 금리 전망 외 기본 성장률·배수는 자체 예시입니다.`;
}
function results(key=selected){return D.stocks.map((s,i)=>M.calculate(s.last,i,settings[key]));}
function update(){if([...document.querySelectorAll('[data-field]')].some(el=>el.value===''||!el.validity.valid))return; let r;try{Object.keys(names).forEach(k=>results(k));r=results();}catch(error){$('#inputStatus').textContent='현재 가정은 가격이 0원 이하가 됩니다. 가정을 조정하세요. 아래 결과는 마지막 유효 설정 기준입니다.';$('#download').hidden=true;return;}$('#inputStatus').textContent='모든 입력이 반영되었습니다. 표시값은 확정 전망이 아닌 조건부 계산입니다.';$('#download').hidden=false;$('#cards').innerHTML=D.stocks.map((s,i)=>`<article class="card" style="--stock:${s.color}"><div class="ticker">${s.symbol} / ${names[selected]}</div><h2>${s.name}</h2><p>12/31 조건부 시나리오</p><div class="price">${money(r[i].target)} <small>원</small></div><div class="delta">기준 종가 대비 ${pct(r[i].change)}</div><p>Q4 시나리오 영업이익 ${r[i].op.toFixed(2)}조원</p><p>비교 기준: Q2 ${M.facts.op[i].toFixed(2)}조원</p></article>`).join('');
 $('#comparison').innerHTML=D.stocks.map((s,i)=>`<tr><td>${s.name}</td><td>${money(s.last)}원</td>${Object.keys(names).map(k=>`<td>${money(results(k)[i].target)}원<br><small>${pct(results(k)[i].change)}</small></td>`).join('')}</tr>`).join('');
 const dates=['2026-09-30','2026-10-31','2026-11-30','2026-12-31'];const fraction=d=>(Date.parse(d)-Date.parse(D.asOf))/(Date.parse(D.target)-Date.parse(D.asOf));
 $('#monthly').innerHTML=D.stocks.map((s,i)=>`<tr><td>${s.name}</td>${dates.map(d=>`<td>${money(M.path(s.last,r[i].target,fraction(d)))}원</td>`).join('')}<td>${pct(r[i].change)}</td></tr>`).join('');
 const i=Number($('#breakdownStock').value),max=Math.max(1,...r[i].contributions.map(Math.abs));$('#bridge').innerHTML=`<div class="muted">${D.stocks[i].name}: ${money(D.stocks[i].last)}원 → ${money(r[i].target)}원 (${names[selected]})</div>`+r[i].contributions.map((v,j)=>`<div class="bridgeRow"><span>${labels[j]}</span><div class="barTrack"><div class="bar ${v<0?'negative':''}" style="width:${Math.abs(v)/max*100}%"></div></div><b>${v>=0?'+':'−'}${money(Math.abs(v))}원</b></div>`).join('');
 const csv=[['종목','시나리오','기준일','연말가격_원','Q4영업이익_조원','한국금리_pct','미국금리_pct','원달러','이익성장_pct','배수변화_pct','기타이익충격_pct','로봇확률_pct','로봇순효과_pct','금리한국계수','금리미국계수','환율계수','모형'],...Object.keys(names).flatMap(k=>D.stocks.map((s,i)=>{let a=settings[k];return [s.name,names[k],D.asOf,Math.round(results(k)[i].target/100)*100,results(k)[i].op.toFixed(4),a.kr,a.us,a.fx,a.growth[i],a.multiple[i],a.other[i],i===0?a.robot:0,i===0?a.robotImpact:0,M.sensitivity.kr[i],M.sensitivity.us[i],M.sensitivity.fx[i],'relative-operating-profit-v2'];}))];$('#download').href='data:text/csv;charset=utf-8,'+encodeURIComponent('\uFEFF'+csv.map(row=>row.join(',')).join('\r\n'));
 chart(r,dates,fraction);
}
function chart(r,dates,fraction){const all=$('#stock').value==='all',indexes=all?[0,1,2]:[Number($('#stock').value)];const W=1080,H=410,L=85,R=28,T=30,B=45,from='2026-03-11';let values=[];const v=(n,i)=>all?n/D.stocks[i].last*100:n;indexes.forEach(i=>{values.push(...D.stocks[i].history.filter(h=>h.date>=from).map(h=>v(h.close,i)),v(r[i].target,i));});let lo=Math.min(...values),hi=Math.max(...values),pad=Math.max(1,(hi-lo)*.12);lo=Math.max(0,lo-pad);hi+=pad;const x=d=>L+(Date.parse(d)-Date.parse(from))/(Date.parse(D.target)-Date.parse(from))*(W-L-R),y=n=>H-B-(n-lo)/(hi-lo)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${names[selected]} 가격 차트"><title>실제 종가와 선택 시나리오. 수치는 아래 표 참조.</title><rect x="${x(D.asOf)}" y="${T}" width="${x(D.target)-x(D.asOf)}" height="${H-T-B}" fill="#203442"/>`;
 for(let j=0;j<=5;j++){let n=lo+(hi-lo)*j/5;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(n)}" y2="${y(n)}" stroke="#334156"/><text x="${L-10}" y="${y(n)+4}" text-anchor="end" font-size="11" fill="#aab9cc">${all?n.toFixed(0):Math.round(n).toLocaleString('ko-KR')}</text>`;}
 for(let month=4;month<=12;month++){let date=`2026-${String(month).padStart(2,'0')}-01`;svg+=`<text x="${x(date)}" y="${H-15}" fill="#aab9cc" font-size="11">${month}월</text>`;}
 svg+=`<text x="${L}" y="17" fill="#aab9cc" font-size="11">${all?'9/11 종가 = 100':'원 (KRW)'}</text><text x="${x(D.asOf)+10}" y="17" fill="#aab9cc" font-size="11">${names[selected]} →</text>`;
 indexes.forEach(i=>{const s=D.stocks[i],h=s.history.filter(h=>h.date>=from),f=[{date:D.asOf,close:s.last},...dates.map(d=>({date:d,close:M.path(s.last,r[i].target,fraction(d))}))],path=a=>a.map((p,j)=>(j?'L':'M')+x(p.date)+','+y(v(p.close,i))).join(' ');svg+=`<path d="${path(h)}" fill="none" stroke="${s.color}" stroke-width="2.5"/><path d="${path(f)}" fill="none" stroke="${s.color}" stroke-width="2.5" stroke-dasharray="6 5"/>`;f.forEach(p=>svg+=`<circle cx="${x(p.date)}" cy="${y(v(p.close,i))}" r="4" fill="${s.color}"><title>${s.name} ${p.date}: ${money(p.close)}원</title></circle>`);});svg+='</svg><p class="muted">'+indexes.map(i=>`<span style="color:${D.stocks[i].color}">● ${D.stocks[i].name}</span>`).join('　')+'</p>';$('#chart').innerHTML=svg;
}
document.querySelectorAll('[data-scenario]').forEach(el=>el.addEventListener('click',()=>{selected=el.dataset.scenario;controls();update();}));$('#reset').addEventListener('click',()=>{settings[selected]=structuredClone(M.presets[selected]);controls();update();});['#stock','#breakdownStock'].forEach(id=>$(id).addEventListener('change',update));controls();update();
